/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed": "#410002",
              "on-secondary-container": "#fffbff",
              "on-tertiary-container": "#848484",
              "surface-container": "#eeeeee",
              "secondary-container": "#e9071e",
              "on-surface-variant": "#4c4546",
              "primary": "#000000",
              "tertiary": "#000000",
              "on-tertiary-fixed-variant": "#474747",
              "on-error-container": "#93000a",
              "primary-container": "#1b1b1b",
              "surface-variant": "#e2e2e2",
              "primary-fixed-dim": "#c6c6c6",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed-dim": "#ffb4ac",
              "tertiary-fixed-dim": "#c6c6c6",
              "surface-dim": "#dadada",
              "inverse-primary": "#c6c6c6",
              "on-tertiary-fixed": "#1b1b1b",
              "inverse-surface": "#2f3131",
              "inverse-on-surface": "#f0f1f1",
              "on-primary": "#ffffff",
              "tertiary-fixed": "#e2e2e2",
              "surface-container-high": "#e8e8e8",
              "on-background": "#1a1c1c",
              "primary-fixed": "#e2e2e2",
              "outline-variant": "#cfc4c5",
              "on-primary-fixed": "#1b1b1b",
              "surface-container-low": "#f3f3f4",
              "secondary": "#bb0015",
              "secondary-fixed": "#ffdad6",
              "on-error": "#ffffff",
              "outline": "#7e7576",
              "on-secondary-fixed-variant": "#93000e",
              "error-container": "#ffdad6",
              "on-primary-fixed-variant": "#474747",
              "error": "#ba1a1a",
              "tertiary-container": "#1b1b1b",
              "on-secondary": "#ffffff",
              "surface-tint": "#5e5e5e",
              "surface-container-highest": "#e2e2e2",
              "surface": "#f9f9f9",
              "on-surface": "#1a1c1c",
              "on-tertiary": "#ffffff",
              "background": "#f9f9f9",
              "surface-bright": "#f9f9f9",
              "on-primary-container": "#848484"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max-width": "1440px",
              "margin-desktop": "48px",
              "unit": "8px",
              "gutter": "24px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "headline-md": ["Cormorant Garamond"],
              "price-tag": ["Montserrat"],
              "display-lg": ["Cormorant Garamond"],
              "headline-lg": ["Cormorant Garamond"],
              "body-md": ["Montserrat"],
              "body-lg": ["Montserrat"],
              "headline-lg-mobile": ["Cormorant Garamond"],
              "label-md": ["Montserrat"]
      },
    },
  },
  plugins: [],
}
